/home/rmkyas002/.conda/envs/yolox_mmdet_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/rmkyas002/.conda/envs/yolox_mmdet_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 2 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
/home/rmkyas002/.conda/envs/yolox_mmdet_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py:557: UserWarning: This DataLoader will create 4 worker processes in total. Our suggested max number of worker in current system is 1, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
Traceback (most recent call last):
  File "/home/rmkyas002/pol_id/detection/mmdetection/tools/train.py", line 121, in <module>
    main()
  File "/home/rmkyas002/pol_id/detection/mmdetection/tools/train.py", line 117, in main
    runner.train()
  File "/home/rmkyas002/.local/lib/python3.9/site-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/home/rmkyas002/.local/lib/python3.9/site-packages/mmengine/runner/loops.py", line 98, in run
    self.run_epoch()
  File "/home/rmkyas002/.local/lib/python3.9/site-packages/mmengine/runner/loops.py", line 114, in run_epoch
    for idx, data_batch in enumerate(self.dataloader):
  File "/home/rmkyas002/.conda/envs/yolox_mmdet_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/rmkyas002/.conda/envs/yolox_mmdet_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/home/rmkyas002/.conda/envs/yolox_mmdet_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/rmkyas002/.conda/envs/yolox_mmdet_env/lib/python3.9/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/rmkyas002/.conda/envs/yolox_mmdet_env/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/rmkyas002/.conda/envs/yolox_mmdet_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rmkyas002/.conda/envs/yolox_mmdet_env/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/rmkyas002/pol_id/detection/mmdetection/mmdet/datasets/dataset_wrappers.py", line 117, in __getitem__
    results = copy.deepcopy(self.dataset[idx])
  File "/home/rmkyas002/.local/lib/python3.9/site-packages/mmengine/dataset/base_dataset.py", line 410, in __getitem__
    data = self.prepare_data(idx)
  File "/home/rmkyas002/.local/lib/python3.9/site-packages/mmengine/dataset/base_dataset.py", line 793, in prepare_data
    return self.pipeline(data_info)
  File "/home/rmkyas002/.local/lib/python3.9/site-packages/mmengine/dataset/base_dataset.py", line 60, in __call__
    data = t(data)
  File "/home/rmkyas002/.conda/envs/yolox_mmdet_env/lib/python3.9/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/rmkyas002/pol_id/detection/mmdetection/mmdet/structures/bbox/box_type.py", line 267, in wrapper
    return func(self, results)
  File "/home/rmkyas002/pol_id/detection/mmdetection/mmdet/datasets/transforms/transforms.py", line 2364, in transform
    assert 'mix_results' in results
AssertionError

